export const SET_IS_LOADING = "SET_IS_LOADING";
export const SET_IS_ERROR = "SET_IS_ERROR";
export const SET_VIDEO_LIST = "SET_VIDEO_LIST";
export const SET_TOTAL_COUNT = "SET_TOTAL_COUNT";
export const SET_FAVOURITE_LIST = "SET_FAVOURITE_LIST";
export const DELETE_FAVOURITE = "DELETE_FAVOURITE";
export const EDIT_FAVOURITE = "EDIT_FAVOURITE";
